import Head from 'next/head'
import Image from 'next/image'
import { HStack, Button } from '@chakra-ui/react'
import { Inter } from "@next/font/google"
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { useUser } from '@auth0/nextjs-auth0/client'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const router = useRouter()

    const { user, error, isLoading } = useUser()
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <HStack>

                </HStack>
            </main>
        </>
    )
}
