import Head from 'next/head'
import { Stack, HStack, useRadio, Text, Button, Image, Flex } from '@chakra-ui/react'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

import { Box } from '@chakra-ui/react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  return (
    <Box bgGradient="radial-gradient(#3D2AD4 5%, #451E86 70%)">
      <Head>
        <title>For Anything E-Sports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&family=Poppins:wght@400;500&display=swap" rel="stylesheet" />
        <link rel="icon" href="logo/fae-icon.png" />
      </Head>

      <main className={styles.main}>
        <Flex mt={20} mx={10} align="center">
          <Box flex="1" p="8" color="white">
            <Text fontFamily="Poppins" fontSize="25" fontWeight="bold" mb={5} mr={15}>
              Freelancing platform for anything esports.
            </Text>
            <Text fontFamily="Poppins" fontSize="15" mb={10} mr={20}>
              FAE brings the spotlight to those who work behind the scenes in esports and gaming to showcase their talent.
            </Text>

            <Flex>
              <Button bg="#6742CE" color="white" size="lg" fontSize="18" fontFamily="Poppins" fontWeight="semibold">
                Browse now
              </Button >
              <Text fontFamily="Poppins" fontSize="32" pl="12" pr="9">or</Text>
              <Button bg="ghost" color="white" size="lg" fontSize="20" fontFamily="Poppins" fontWeight="semibold">Create an account</Button>
            </Flex>
          </Box>

          <Box flex="1" p="8">
            <Image
              borderRadius="20px"
              boxSize="150px"
              src="homepage-imgs/homepage-img.png"
              alt="e-sports tournament"
            />
          </Box>
        </Flex>
      </main>
    </Box>
  )
}
